var quito = [{
   "cod":"200",
   "message":0,
   "cnt":40,
   "list":[
      {
         "dt":1579024800,
         "main":{
            "temp":66.6,
            "feels_like":62.33,
            "temp_min":66.6,
            "temp_max":67.06,
            "pressure":1011,
            "sea_level":1011,
            "grnd_level":750,
            "humidity":61,
            "temp_kf":-0.26
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":19
         },
         "wind":{
            "speed":9.08,
            "deg":320
         },
         "rain":{
            "3h":0.44
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-14 18:00:00"
      },
      {
         "dt":1579035600,
         "main":{
            "temp":62.06,
            "feels_like":58.44,
            "temp_min":62.06,
            "temp_max":62.42,
            "pressure":1009,
            "sea_level":1009,
            "grnd_level":748,
            "humidity":76,
            "temp_kf":-0.2
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":43
         },
         "wind":{
            "speed":8.86,
            "deg":318
         },
         "rain":{
            "3h":1.44
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-14 21:00:00"
      },
      {
         "dt":1579046400,
         "main":{
            "temp":56.62,
            "feels_like":55.33,
            "temp_min":56.62,
            "temp_max":56.86,
            "pressure":1011,
            "sea_level":1011,
            "grnd_level":749,
            "humidity":90,
            "temp_kf":-0.13
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":67
         },
         "wind":{
            "speed":4.34,
            "deg":316
         },
         "rain":{
            "3h":0.94
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-15 00:00:00"
      },
      {
         "dt":1579057200,
         "main":{
            "temp":56.17,
            "feels_like":55.85,
            "temp_min":56.17,
            "temp_max":56.3,
            "pressure":1013,
            "sea_level":1013,
            "grnd_level":751,
            "humidity":90,
            "temp_kf":-0.07
         },
         "weather":[
            {
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":78
         },
         "wind":{
            "speed":2.39,
            "deg":11
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-15 03:00:00"
      },
      {
         "dt":1579068000,
         "main":{
            "temp":55.63,
            "feels_like":54.7,
            "temp_min":55.63,
            "temp_max":55.63,
            "pressure":1013,
            "sea_level":1013,
            "grnd_level":750,
            "humidity":79,
            "temp_kf":0
         },
         "weather":[
            {
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":61
         },
         "wind":{
            "speed":1.43,
            "deg":63
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-15 06:00:00"
      },
      {
         "dt":1579078800,
         "main":{
            "temp":53.91,
            "feels_like":51.48,
            "temp_min":53.91,
            "temp_max":53.91,
            "pressure":1012,
            "sea_level":1012,
            "grnd_level":749,
            "humidity":74,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.59,
            "deg":129
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-15 09:00:00"
      },
      {
         "dt":1579089600,
         "main":{
            "temp":54.97,
            "feels_like":51.66,
            "temp_min":54.97,
            "temp_max":54.97,
            "pressure":1013,
            "sea_level":1013,
            "grnd_level":750,
            "humidity":69,
            "temp_kf":0
         },
         "weather":[
            {
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02d"
            }
         ],
         "clouds":{
            "all":23
         },
         "wind":{
            "speed":3.8,
            "deg":118
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-15 12:00:00"
      },
      {
         "dt":1579100400,
         "main":{
            "temp":67.5,
            "feels_like":65.46,
            "temp_min":67.5,
            "temp_max":67.5,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":751,
            "humidity":47,
            "temp_kf":0
         },
         "weather":[
            {
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02d"
            }
         ],
         "clouds":{
            "all":17
         },
         "wind":{
            "speed":2.19,
            "deg":1
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-15 15:00:00"
      },
      {
         "dt":1579111200,
         "main":{
            "temp":68.94,
            "feels_like":65.34,
            "temp_min":68.94,
            "temp_max":68.94,
            "pressure":1010,
            "sea_level":1010,
            "grnd_level":750,
            "humidity":56,
            "temp_kf":0
         },
         "weather":[
            {
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02d"
            }
         ],
         "clouds":{
            "all":15
         },
         "wind":{
            "speed":7.83,
            "deg":330
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-15 18:00:00"
      },
      {
         "dt":1579122000,
         "main":{
            "temp":63.86,
            "feels_like":61.25,
            "temp_min":63.86,
            "temp_max":63.86,
            "pressure":1008,
            "sea_level":1008,
            "grnd_level":748,
            "humidity":73,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":58
         },
         "wind":{
            "speed":7.4,
            "deg":309
         },
         "rain":{
            "3h":0.81
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-15 21:00:00"
      },
      {
         "dt":1579132800,
         "main":{
            "temp":57.92,
            "feels_like":57.18,
            "temp_min":57.92,
            "temp_max":57.92,
            "pressure":1011,
            "sea_level":1011,
            "grnd_level":750,
            "humidity":91,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":57
         },
         "wind":{
            "speed":4.25,
            "deg":331
         },
         "rain":{
            "3h":0.69
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-16 00:00:00"
      },
      {
         "dt":1579143600,
         "main":{
            "temp":56.93,
            "feels_like":57.11,
            "temp_min":56.93,
            "temp_max":56.93,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":752,
            "humidity":85,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":58
         },
         "wind":{
            "speed":1.05,
            "deg":18
         },
         "rain":{
            "3h":0.5
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-16 03:00:00"
      },
      {
         "dt":1579154400,
         "main":{
            "temp":57,
            "feels_like":57.02,
            "temp_min":57,
            "temp_max":57,
            "pressure":1013,
            "sea_level":1013,
            "grnd_level":751,
            "humidity":82,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":45
         },
         "wind":{
            "speed":0.87,
            "deg":326
         },
         "rain":{
            "3h":0.13
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-16 06:00:00"
      },
      {
         "dt":1579165200,
         "main":{
            "temp":54.95,
            "feels_like":54.91,
            "temp_min":54.95,
            "temp_max":54.95,
            "pressure":1012,
            "sea_level":1012,
            "grnd_level":750,
            "humidity":85,
            "temp_kf":0
         },
         "weather":[
            {
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03n"
            }
         ],
         "clouds":{
            "all":38
         },
         "wind":{
            "speed":0.47,
            "deg":8
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-16 09:00:00"
      },
      {
         "dt":1579176000,
         "main":{
            "temp":56.07,
            "feels_like":53.78,
            "temp_min":56.07,
            "temp_max":56.07,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":751,
            "humidity":72,
            "temp_kf":0
         },
         "weather":[
            {
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03d"
            }
         ],
         "clouds":{
            "all":36
         },
         "wind":{
            "speed":2.91,
            "deg":144
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-16 12:00:00"
      },
      {
         "dt":1579186800,
         "main":{
            "temp":68.02,
            "feels_like":66,
            "temp_min":68.02,
            "temp_max":68.02,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":752,
            "humidity":48,
            "temp_kf":0
         },
         "weather":[
            {
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02d"
            }
         ],
         "clouds":{
            "all":17
         },
         "wind":{
            "speed":2.59,
            "deg":42
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-16 15:00:00"
      },
      {
         "dt":1579197600,
         "main":{
            "temp":70.5,
            "feels_like":68.16,
            "temp_min":70.5,
            "temp_max":70.5,
            "pressure":1012,
            "sea_level":1012,
            "grnd_level":750,
            "humidity":51,
            "temp_kf":0
         },
         "weather":[
            {
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02d"
            }
         ],
         "clouds":{
            "all":20
         },
         "wind":{
            "speed":5.03,
            "deg":359
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-16 18:00:00"
      },
      {
         "dt":1579208400,
         "main":{
            "temp":62.6,
            "feels_like":60.13,
            "temp_min":62.6,
            "temp_max":62.6,
            "pressure":1010,
            "sea_level":1010,
            "grnd_level":749,
            "humidity":80,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":56
         },
         "wind":{
            "speed":7.92,
            "deg":311
         },
         "rain":{
            "3h":0.44
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-16 21:00:00"
      },
      {
         "dt":1579219200,
         "main":{
            "temp":58.77,
            "feels_like":58.41,
            "temp_min":58.77,
            "temp_max":58.77,
            "pressure":1012,
            "sea_level":1012,
            "grnd_level":750,
            "humidity":87,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":64
         },
         "wind":{
            "speed":3.36,
            "deg":322
         },
         "rain":{
            "3h":0.37
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-17 00:00:00"
      },
      {
         "dt":1579230000,
         "main":{
            "temp":58.32,
            "feels_like":58.35,
            "temp_min":58.32,
            "temp_max":58.32,
            "pressure":1015,
            "sea_level":1015,
            "grnd_level":752,
            "humidity":82,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":57
         },
         "wind":{
            "speed":1.52,
            "deg":4
         },
         "rain":{
            "3h":0.13
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-17 03:00:00"
      },
      {
         "dt":1579240800,
         "main":{
            "temp":55.99,
            "feels_like":55.74,
            "temp_min":55.99,
            "temp_max":55.99,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":751,
            "humidity":79,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":41
         },
         "wind":{
            "speed":0.4,
            "deg":25
         },
         "rain":{
            "3h":0.06
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-17 06:00:00"
      },
      {
         "dt":1579251600,
         "main":{
            "temp":55.76,
            "feels_like":54.57,
            "temp_min":55.76,
            "temp_max":55.76,
            "pressure":1013,
            "sea_level":1013,
            "grnd_level":750,
            "humidity":79,
            "temp_kf":0
         },
         "weather":[
            {
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02n"
            }
         ],
         "clouds":{
            "all":16
         },
         "wind":{
            "speed":1.95,
            "deg":110
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-17 09:00:00"
      },
      {
         "dt":1579262400,
         "main":{
            "temp":56.59,
            "feels_like":54.34,
            "temp_min":56.59,
            "temp_max":56.59,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":751,
            "humidity":71,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":8
         },
         "wind":{
            "speed":2.89,
            "deg":135
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-17 12:00:00"
      },
      {
         "dt":1579273200,
         "main":{
            "temp":68.22,
            "feels_like":66.83,
            "temp_min":68.22,
            "temp_max":68.22,
            "pressure":1015,
            "sea_level":1015,
            "grnd_level":752,
            "humidity":50,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":3
         },
         "wind":{
            "speed":2.08,
            "deg":20
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-17 15:00:00"
      },
      {
         "dt":1579284000,
         "main":{
            "temp":70.03,
            "feels_like":69.3,
            "temp_min":70.03,
            "temp_max":70.03,
            "pressure":1012,
            "sea_level":1012,
            "grnd_level":750,
            "humidity":56,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":20
         },
         "wind":{
            "speed":3.29,
            "deg":351
         },
         "rain":{
            "3h":0.38
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-17 18:00:00"
      },
      {
         "dt":1579294800,
         "main":{
            "temp":65.34,
            "feels_like":64.33,
            "temp_min":65.34,
            "temp_max":65.34,
            "pressure":1009,
            "sea_level":1009,
            "grnd_level":749,
            "humidity":67,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":75
         },
         "wind":{
            "speed":4.05,
            "deg":347
         },
         "rain":{
            "3h":0.69
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-17 21:00:00"
      },
      {
         "dt":1579305600,
         "main":{
            "temp":61.14,
            "feels_like":60.21,
            "temp_min":61.14,
            "temp_max":61.14,
            "pressure":1012,
            "sea_level":1012,
            "grnd_level":750,
            "humidity":75,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":68
         },
         "wind":{
            "speed":3.4,
            "deg":19
         },
         "rain":{
            "3h":0.31
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-18 00:00:00"
      },
      {
         "dt":1579316400,
         "main":{
            "temp":58.06,
            "feels_like":55.85,
            "temp_min":58.06,
            "temp_max":58.06,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":751,
            "humidity":73,
            "temp_kf":0
         },
         "weather":[
            {
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03n"
            }
         ],
         "clouds":{
            "all":29
         },
         "wind":{
            "speed":3.8,
            "deg":81
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-18 03:00:00"
      },
      {
         "dt":1579327200,
         "main":{
            "temp":57.02,
            "feels_like":56.1,
            "temp_min":57.02,
            "temp_max":57.02,
            "pressure":1012,
            "sea_level":1012,
            "grnd_level":750,
            "humidity":74,
            "temp_kf":0
         },
         "weather":[
            {
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03n"
            }
         ],
         "clouds":{
            "all":30
         },
         "wind":{
            "speed":1.23,
            "deg":53
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-18 06:00:00"
      },
      {
         "dt":1579338000,
         "main":{
            "temp":55.51,
            "feels_like":54.82,
            "temp_min":55.51,
            "temp_max":55.51,
            "pressure":1011,
            "sea_level":1011,
            "grnd_level":749,
            "humidity":78,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":6
         },
         "wind":{
            "speed":0.76,
            "deg":105
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-18 09:00:00"
      },
      {
         "dt":1579348800,
         "main":{
            "temp":56.12,
            "feels_like":55.81,
            "temp_min":56.12,
            "temp_max":56.12,
            "pressure":1013,
            "sea_level":1013,
            "grnd_level":750,
            "humidity":80,
            "temp_kf":0
         },
         "weather":[
            {
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02d"
            }
         ],
         "clouds":{
            "all":15
         },
         "wind":{
            "speed":0.69,
            "deg":30
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-18 12:00:00"
      },
      {
         "dt":1579359600,
         "main":{
            "temp":67.53,
            "feels_like":65.8,
            "temp_min":67.53,
            "temp_max":67.53,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":751,
            "humidity":55,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":7
         },
         "wind":{
            "speed":3.6,
            "deg":31
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-18 15:00:00"
      },
      {
         "dt":1579370400,
         "main":{
            "temp":70.68,
            "feels_like":69.08,
            "temp_min":70.68,
            "temp_max":70.68,
            "pressure":1011,
            "sea_level":1011,
            "grnd_level":749,
            "humidity":51,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":23
         },
         "wind":{
            "speed":3.8,
            "deg":22
         },
         "rain":{
            "3h":0.31
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-18 18:00:00"
      },
      {
         "dt":1579381200,
         "main":{
            "temp":62.62,
            "feels_like":60.87,
            "temp_min":62.62,
            "temp_max":62.62,
            "pressure":1008,
            "sea_level":1008,
            "grnd_level":748,
            "humidity":78,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":96
         },
         "wind":{
            "speed":6.22,
            "deg":321
         },
         "rain":{
            "3h":0.31
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-18 21:00:00"
      },
      {
         "dt":1579392000,
         "main":{
            "temp":58.55,
            "feels_like":57.9,
            "temp_min":58.55,
            "temp_max":58.55,
            "pressure":1011,
            "sea_level":1011,
            "grnd_level":750,
            "humidity":90,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":94
         },
         "wind":{
            "speed":4.25,
            "deg":318
         },
         "rain":{
            "3h":0.31
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-19 00:00:00"
      },
      {
         "dt":1579402800,
         "main":{
            "temp":58.33,
            "feels_like":58.1,
            "temp_min":58.33,
            "temp_max":58.33,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":751,
            "humidity":83,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":2.19,
            "deg":17
         },
         "rain":{
            "3h":0.25
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-19 03:00:00"
      },
      {
         "dt":1579413600,
         "main":{
            "temp":55.44,
            "feels_like":54.75,
            "temp_min":55.44,
            "temp_max":55.44,
            "pressure":1012,
            "sea_level":1012,
            "grnd_level":750,
            "humidity":85,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":94
         },
         "wind":{
            "speed":1.86,
            "deg":334
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-19 06:00:00"
      },
      {
         "dt":1579424400,
         "main":{
            "temp":55.44,
            "feels_like":55.13,
            "temp_min":55.44,
            "temp_max":55.44,
            "pressure":1011,
            "sea_level":1011,
            "grnd_level":749,
            "humidity":86,
            "temp_kf":0
         },
         "weather":[
            {
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":75
         },
         "wind":{
            "speed":1.34,
            "deg":345
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2020-01-19 09:00:00"
      },
      {
         "dt":1579435200,
         "main":{
            "temp":56.05,
            "feels_like":55.98,
            "temp_min":56.05,
            "temp_max":56.05,
            "pressure":1012,
            "sea_level":1012,
            "grnd_level":750,
            "humidity":81,
            "temp_kf":0
         },
         "weather":[
            {
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04d"
            }
         ],
         "clouds":{
            "all":62
         },
         "wind":{
            "speed":0.43,
            "deg":217
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-19 12:00:00"
      },
      {
         "dt":1579446000,
         "main":{
            "temp":64.69,
            "feels_like":62.78,
            "temp_min":64.69,
            "temp_max":64.69,
            "pressure":1014,
            "sea_level":1014,
            "grnd_level":752,
            "humidity":65,
            "temp_kf":0
         },
         "weather":[
            {
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03d"
            }
         ],
         "clouds":{
            "all":49
         },
         "wind":{
            "speed":4.85,
            "deg":330
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2020-01-19 15:00:00"
      }
   ],
   "city":{
      "id":3652462,
      "name":"Quito",
      "coord":{
         "lat":-0.2299,
         "lon":-78.5249
      },
      "country":"EC",
      "population":1399814,
      "timezone":-18000,
      "sunrise":1579000731,
      "sunset":1579044402
   }
}]; 